### ISSUE TITLE
Bottom right cell not displayed

### ISSUE THREAD

**Issue by lewis-weinberger** [lewis-weinberger/crabs#2]
I think the iterator over the map instance is not reaching the final cell, and hence the bottom right cell of the map is not displayed (and can't be reached by the cursor).

However my attempts to figure out this problem have not yet been successful!

```rust
impl Iterator for Map {
    type Item = (usize, usize, char);

    fn next(&mut self) -> Option<(usize, usize, char)> {
        if (self.index[1] + 1) * (self.index[0] + 1) < self.dimensions[0] * self.dimensions[1] {
            // Current position
            let y = self.index[0];
            let x = self.index[1];

            // Current character
            let ch = self.layout[y][x].to_char();

            // Advance position in map
            if self.index[1] + 1 == self.dimensions[1] {
                if self.index[0] + 1 < self.dimensions[0] {
                    self.index[0] += 1;
                    self.index[1] = 0;
                }
            } else {
                self.index[1] += 1;
            }

            Some((y, x, ch))
        } else {
            None
        }
    }
}
```

**Comment by sam-kirby** [comment]
Taking a 5x5 grid as an example, the last element will have index[0]=4 and index[1]=4, thus (index[0]+1)(index[1]+1) = 25 == number of elements, so it fails your first condition and returns None.

If you change the condition to less than or equal to however, it breaks for a different reason. You're now going to try and visit index[0]=5, index[1]=0, which doesn't work.

**Comment by lewis-weinberger** [comment]
Yes exactly!

The first condition should be `<=` rather than `==`, but then we end up indexing out of bounds. 

It actually should be something like:

```rust
(self.index[1]*self.dimensions[0] + self.index[0]) < self.dimensions[0] * self.dimensions[1]
```

The final cell would be `index[1] = dimensions[1] - 1` and `index[0] = dimensions[0] - 1` giving:

```rust
(self.dimensions[1] - 1)*self.dimensions[0] + self.dimensions[0] - 1
```
which is 1 less than `self.dimensions[0] * self.dimensions[1]`, so the final cell would be included. But this crashes the program with:

```rust
Error: Os { code: 5, kind: Other, message: "Input/output error" }
```
which comes from [writing to stdout](https://github.com/lewis-weinberger/crabs/blob/master/src/main.rs#L72-L92). Unfortunately this "Other" error message is not particularly helpful 😝
